package entity;
// Generated May 11, 2019 8:29:17 PM by Hibernate Tools 4.3.1



/**
 * Akun generated by hbm2java
 */
public class Akun  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private String email;
     private String nama;
     private String noTelp;
     private String gambar;
     private String alamat;

    public Akun() {
    }

    public Akun(String username, String password, String email, String nama, String noTelp, String gambar, String alamat) {
       this.username = username;
       this.password = password;
       this.email = email;
       this.nama = nama;
       this.noTelp = noTelp;
       this.gambar = gambar;
       this.alamat = alamat;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getNoTelp() {
        return this.noTelp;
    }
    
    public void setNoTelp(String noTelp) {
        this.noTelp = noTelp;
    }
    public String getGambar() {
        return this.gambar;
    }
    
    public void setGambar(String gambar) {
        this.gambar = gambar;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }




}


