package entity;
// Generated May 15, 2019 9:13:58 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Akun generated by hbm2java
 */
public class Akun  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private String email;
     private String nama;
     private String noTelp;
     private String gambar;
     private String alamat;
     private Integer status;
     private int no;
     
     private Set pembibitans = new HashSet(0);
     private Set bantuans = new HashSet(0);
     private Set tawarans = new HashSet(0);
     private Set panens = new HashSet(0);
     private Set panens_1 = new HashSet(0);
     private Set panens_2 = new HashSet(0);
     private Set panens_3 = new HashSet(0);
     private Set panens_4 = new HashSet(0);
     private Set pemupukans = new HashSet(0);
     private Set transaksis = new HashSet(0);
     private Set preorders = new HashSet(0);
     private Set penanamans = new HashSet(0);
     private Set pascaPanens = new HashSet(0);

    public Akun(int no,String username,String email, String nama, String noTelp, String alamat) {
        this.no=no;
        this.username = username;
        this.email = email;
        this.nama = nama;
        this.noTelp = noTelp;
        this.alamat = alamat;
    }
    public Akun(){
        
    }


    public Akun(String username, String password, String email, String nama, String noTelp, String gambar, String alamat,Integer status, Set pembibitans, Set bantuans, Set tawarans, Set panens, Set panens_1, Set panens_2, Set panens_3, Set panens_4, Set pemupukans, Set transaksis, Set preorders, Set penanamans, Set pascaPanens) {
       this.username = username;
       this.password = password;
       this.email = email;
       this.nama = nama;
       this.noTelp = noTelp;
       this.gambar = gambar;
       this.alamat = alamat;
       this.status=status;
       this.pembibitans = pembibitans;
       this.bantuans = bantuans;
       this.tawarans = tawarans;
       this.panens = panens;
       this.panens_1 = panens_1;
       this.panens_2 = panens_2;
       this.panens_3 = panens_3;
       this.panens_4 = panens_4;
       this.pemupukans = pemupukans;
       this.transaksis = transaksis;
       this.preorders = preorders;
       this.penanamans = penanamans;
       this.pascaPanens = pascaPanens;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getNoTelp() {
        return this.noTelp;
    }
    
    public void setNoTelp(String noTelp) {
        this.noTelp = noTelp;
    }
    public String getGambar() {
        return this.gambar;
    }
    
    public void setGambar(String gambar) {
        this.gambar = gambar;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public Set getPembibitans() {
        return this.pembibitans;
    }
    
    public void setPembibitans(Set pembibitans) {
        this.pembibitans = pembibitans;
    }
    public Set getBantuans() {
        return this.bantuans;
    }
    
    public void setBantuans(Set bantuans) {
        this.bantuans = bantuans;
    }
    public Set getTawarans() {
        return this.tawarans;
    }
    
    public void setTawarans(Set tawarans) {
        this.tawarans = tawarans;
    }
    public Set getPanens() {
        return this.panens;
    }
    
    public void setPanens(Set panens) {
        this.panens = panens;
    }
    public Set getPanens_1() {
        return this.panens_1;
    }
    
    public void setPanens_1(Set panens_1) {
        this.panens_1 = panens_1;
    }
    public Set getPanens_2() {
        return this.panens_2;
    }
    
    public void setPanens_2(Set panens_2) {
        this.panens_2 = panens_2;
    }
    public Set getPanens_3() {
        return this.panens_3;
    }
    
    public void setPanens_3(Set panens_3) {
        this.panens_3 = panens_3;
    }
    public Set getPanens_4() {
        return this.panens_4;
    }
    
    public void setPanens_4(Set panens_4) {
        this.panens_4 = panens_4;
    }
    public Set getPemupukans() {
        return this.pemupukans;
    }
    
    public void setPemupukans(Set pemupukans) {
        this.pemupukans = pemupukans;
    }
    public Set getTransaksis() {
        return this.transaksis;
    }
    
    public void setTransaksis(Set transaksis) {
        this.transaksis = transaksis;
    }
    public Set getPreorders() {
        return this.preorders;
    }
    
    public void setPreorders(Set preorders) {
        this.preorders = preorders;
    }
    public Set getPenanamans() {
        return this.penanamans;
    }
    
    public void setPenanamans(Set penanamans) {
        this.penanamans = penanamans;
    }
    public Set getPascaPanens() {
        return this.pascaPanens;
    }
    
    public void setPascaPanens(Set pascaPanens) {
        this.pascaPanens = pascaPanens;
    }




}


