package entity;
// Generated May 15, 2019 9:13:58 PM by Hibernate Tools 4.3.1



/**
 * Bantuan generated by hbm2java
 */
public class Bantuan  implements java.io.Serializable {


     private Integer id;
     private Akun akun;
     private String jenisBantuan;
     private String jenisTanaman;
     private String deskripsi;

    public Bantuan() {
    }

    public Bantuan(Akun akun, String jenisBantuan, String jenisTanaman, String deskripsi) {
       this.akun = akun;
       this.jenisBantuan = jenisBantuan;
       this.jenisTanaman = jenisTanaman;
       this.deskripsi = deskripsi;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Akun getAkun() {
        return this.akun;
    }
    
    public void setAkun(Akun akun) {
        this.akun = akun;
    }
    public String getJenisBantuan() {
        return this.jenisBantuan;
    }
    
    public void setJenisBantuan(String jenisBantuan) {
        this.jenisBantuan = jenisBantuan;
    }
    public String getJenisTanaman() {
        return this.jenisTanaman;
    }
    
    public void setJenisTanaman(String jenisTanaman) {
        this.jenisTanaman = jenisTanaman;
    }
    public String getDeskripsi() {
        return this.deskripsi;
    }
    
    public void setDeskripsi(String deskripsi) {
        this.deskripsi = deskripsi;
    }




}


