package entity;
// Generated May 11, 2019 8:29:17 PM by Hibernate Tools 4.3.1


import java.sql.Clob;

/**
 * Bantuan generated by hbm2java
 */
public class Bantuan  implements java.io.Serializable {


     private Integer id;
     private Integer idAkun;
     private String jenisBantuan;
     private Clob deskripsi;
     private String jenisTanaman;

    public Bantuan() {
    }

    public Bantuan(Integer idAkun, String jenisBantuan, Clob deskripsi, String jenisTanaman) {
       this.idAkun = idAkun;
       this.jenisBantuan = jenisBantuan;
       this.deskripsi = deskripsi;
       this.jenisTanaman = jenisTanaman;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getIdAkun() {
        return this.idAkun;
    }
    
    public void setIdAkun(Integer idAkun) {
        this.idAkun = idAkun;
    }
    public String getJenisBantuan() {
        return this.jenisBantuan;
    }
    
    public void setJenisBantuan(String jenisBantuan) {
        this.jenisBantuan = jenisBantuan;
    }
    public Clob getDeskripsi() {
        return this.deskripsi;
    }
    
    public void setDeskripsi(Clob deskripsi) {
        this.deskripsi = deskripsi;
    }
    public String getJenisTanaman() {
        return this.jenisTanaman;
    }
    
    public void setJenisTanaman(String jenisTanaman) {
        this.jenisTanaman = jenisTanaman;
    }




}


