package entity;
// Generated May 11, 2019 8:29:17 PM by Hibernate Tools 4.3.1



/**
 * Pembibitan generated by hbm2java
 */
public class Pembibitan  implements java.io.Serializable {


     private Integer id;
     private String createdAt;
     private Double ukuranLahan;
     private String jenisTanaman;
     private String tanggalMulaiPembibitan;
     private String tanggalSelesaiPembibitan;
     private String deskripsiTanaman;
     private String lokasi;
     private String caraPembibitan;
     private String status;
     private String bookedStatus;
     int no;
    public Pembibitan() {
    }

    public Pembibitan(int no,String createdAt, Double ukuranLahan, String jenisTanaman, String tanggalMulaiPembibitan, String tanggalSelesaiPembibitan, String deskripsiTanaman, String lokasi, String caraPembibitan, String status, String bookedStatus) {
       this.no=no;
        this.createdAt = createdAt;
       this.ukuranLahan = ukuranLahan;
       this.jenisTanaman = jenisTanaman;
       this.tanggalMulaiPembibitan = tanggalMulaiPembibitan;
       this.tanggalSelesaiPembibitan = tanggalSelesaiPembibitan;
       this.deskripsiTanaman = deskripsiTanaman;
       this.lokasi = lokasi;
       this.caraPembibitan = caraPembibitan;
       this.status = status;
       this.bookedStatus = bookedStatus;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }
    public Double getUkuranLahan() {
        return this.ukuranLahan;
    }
    
    public void setUkuranLahan(Double ukuranLahan) {
        this.ukuranLahan = ukuranLahan;
    }
    public String getJenisTanaman() {
        return this.jenisTanaman;
    }
    
    public void setJenisTanaman(String jenisTanaman) {
        this.jenisTanaman = jenisTanaman;
    }
    public String getTanggalMulaiPembibitan() {
        return this.tanggalMulaiPembibitan;
    }
    
    public void setTanggalMulaiPembibitan(String tanggalMulaiPembibitan) {
        this.tanggalMulaiPembibitan = tanggalMulaiPembibitan;
    }
    public String getTanggalSelesaiPembibitan() {
        return this.tanggalSelesaiPembibitan;
    }
    
    public void setTanggalSelesaiPembibitan(String tanggalSelesaiPembibitan) {
        this.tanggalSelesaiPembibitan = tanggalSelesaiPembibitan;
    }
    public String getDeskripsiTanaman() {
        return this.deskripsiTanaman;
    }
    
    public void setDeskripsiTanaman(String deskripsiTanaman) {
        this.deskripsiTanaman = deskripsiTanaman;
    }
    public String getLokasi() {
        return this.lokasi;
    }
    
    public void setLokasi(String lokasi) {
        this.lokasi = lokasi;
    }
    public String getCaraPembibitan() {
        return this.caraPembibitan;
    }
    
    public void setCaraPembibitan(String caraPembibitan) {
        this.caraPembibitan = caraPembibitan;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getBookedStatus() {
        return this.bookedStatus;
    }
    
    public void setBookedStatus(String bookedStatus) {
        this.bookedStatus = bookedStatus;
    }




}


