package entity;
// Generated May 11, 2019 8:29:17 PM by Hibernate Tools 4.3.1



/**
 * Preorder generated by hbm2java
 */
public class Preorder  implements java.io.Serializable {


     private Integer id;
     private Integer idAkun;
     private Integer idTanaman;
     private String status;
     private String bookedStatus;

    public Preorder() {
    }

    public Preorder(Integer idAkun, Integer idTanaman, String status, String bookedStatus) {
       this.idAkun = idAkun;
       this.idTanaman = idTanaman;
       this.status = status;
       this.bookedStatus = bookedStatus;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getIdAkun() {
        return this.idAkun;
    }
    
    public void setIdAkun(Integer idAkun) {
        this.idAkun = idAkun;
    }
    public Integer getIdTanaman() {
        return this.idTanaman;
    }
    
    public void setIdTanaman(Integer idTanaman) {
        this.idTanaman = idTanaman;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getBookedStatus() {
        return this.bookedStatus;
    }
    
    public void setBookedStatus(String bookedStatus) {
        this.bookedStatus = bookedStatus;
    }




}


