package entity;
// Generated May 15, 2019 9:13:58 PM by Hibernate Tools 4.3.1



/**
 * Preorder generated by hbm2java
 */
public class Preorder  implements java.io.Serializable {


     private Integer id;
     private Akun akun;
     private Integer idTanaman;
     private String status;
     private String bookedStatus;

    public Preorder() {
    }

    public Preorder(Akun akun, Integer idTanaman, String status, String bookedStatus) {
       this.akun = akun;
       this.idTanaman = idTanaman;
       this.status = status;
       this.bookedStatus = bookedStatus;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Akun getAkun() {
        return this.akun;
    }
    
    public void setAkun(Akun akun) {
        this.akun = akun;
    }
    public Integer getIdTanaman() {
        return this.idTanaman;
    }
    
    public void setIdTanaman(Integer idTanaman) {
        this.idTanaman = idTanaman;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getBookedStatus() {
        return this.bookedStatus;
    }
    
    public void setBookedStatus(String bookedStatus) {
        this.bookedStatus = bookedStatus;
    }




}


