package entity;
// Generated May 15, 2019 9:13:58 PM by Hibernate Tools 4.3.1



/**
 * Produk generated by hbm2java
 */
public class Produk  implements java.io.Serializable {


     private Integer id;
     private String namaProduk;
     private Integer jumlah;
     private Integer harga;
     private Integer idAkun;
     private String deskripsi;
     private String status;
     private String gambar;

    public Produk() {
    }

    public Produk(String namaProduk, Integer jumlah, Integer harga, Integer idAkun, String deskripsi, String status, String gambar) {
       this.namaProduk = namaProduk;
       this.jumlah = jumlah;
       this.harga = harga;
       this.idAkun = idAkun;
       this.deskripsi = deskripsi;
       this.status = status;
       this.gambar = gambar;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNamaProduk() {
        return this.namaProduk;
    }
    
    public void setNamaProduk(String namaProduk) {
        this.namaProduk = namaProduk;
    }
    public Integer getJumlah() {
        return this.jumlah;
    }
    
    public void setJumlah(Integer jumlah) {
        this.jumlah = jumlah;
    }
    public Integer getHarga() {
        return this.harga;
    }
    
    public void setHarga(Integer harga) {
        this.harga = harga;
    }
    public Integer getIdAkun() {
        return this.idAkun;
    }
    
    public void setIdAkun(Integer idAkun) {
        this.idAkun = idAkun;
    }
    public String getDeskripsi() {
        return this.deskripsi;
    }
    
    public void setDeskripsi(String deskripsi) {
        this.deskripsi = deskripsi;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getGambar() {
        return this.gambar;
    }
    
    public void setGambar(String gambar) {
        this.gambar = gambar;
    }




}


