package entity;
// Generated May 11, 2019 8:29:17 PM by Hibernate Tools 4.3.1



/**
 * Requestregister generated by hbm2java
 */
public class Requestregister  implements java.io.Serializable {


     private Integer id;
     private String nama;
     private String username;
     private String password;
     private String email;
     private String notelp;
     private String alamat;
     private String roles;
     private String createdAt;

    public Requestregister() {
    }

    public Requestregister(String nama, String username, String password, String email, String notelp, String alamat, String roles, String createdAt) {
       this.nama = nama;
       this.username = username;
       this.password = password;
       this.email = email;
       this.notelp = notelp;
       this.alamat = alamat;
       this.roles = roles;
       this.createdAt = createdAt;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNotelp() {
        return this.notelp;
    }
    
    public void setNotelp(String notelp) {
        this.notelp = notelp;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getRoles() {
        return this.roles;
    }
    
    public void setRoles(String roles) {
        this.roles = roles;
    }
    public String getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }




}


