package entity;
// Generated May 11, 2019 8:29:17 PM by Hibernate Tools 4.3.1



/**
 * Tawaran generated by hbm2java
 */
public class Tawaran  implements java.io.Serializable {


     private Integer id;
     private Integer idAkun;
     private Integer hargaTawaran;
     private Integer tanamanId;
     private String createdAt;

    public Tawaran() {
    }

    public Tawaran(Integer idAkun, Integer hargaTawaran, Integer tanamanId, String createdAt) {
       this.idAkun = idAkun;
       this.hargaTawaran = hargaTawaran;
       this.tanamanId = tanamanId;
       this.createdAt = createdAt;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getIdAkun() {
        return this.idAkun;
    }
    
    public void setIdAkun(Integer idAkun) {
        this.idAkun = idAkun;
    }
    public Integer getHargaTawaran() {
        return this.hargaTawaran;
    }
    
    public void setHargaTawaran(Integer hargaTawaran) {
        this.hargaTawaran = hargaTawaran;
    }
    public Integer getTanamanId() {
        return this.tanamanId;
    }
    
    public void setTanamanId(Integer tanamanId) {
        this.tanamanId = tanamanId;
    }
    public String getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }




}


