package entity;
// Generated May 11, 2019 8:29:17 PM by Hibernate Tools 4.3.1



/**
 * Transaksi generated by hbm2java
 */
public class Transaksi  implements java.io.Serializable {


     private Integer id;
     private Integer idAkun;
     private Integer hargaTotal;
     private Integer tanamanId;
     private String createdAt;

    public Transaksi() {
    }

    public Transaksi(Integer idAkun, Integer hargaTotal, Integer tanamanId, String createdAt) {
       this.idAkun = idAkun;
       this.hargaTotal = hargaTotal;
       this.tanamanId = tanamanId;
       this.createdAt = createdAt;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getIdAkun() {
        return this.idAkun;
    }
    
    public void setIdAkun(Integer idAkun) {
        this.idAkun = idAkun;
    }
    public Integer getHargaTotal() {
        return this.hargaTotal;
    }
    
    public void setHargaTotal(Integer hargaTotal) {
        this.hargaTotal = hargaTotal;
    }
    public Integer getTanamanId() {
        return this.tanamanId;
    }
    
    public void setTanamanId(Integer tanamanId) {
        this.tanamanId = tanamanId;
    }
    public String getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }




}


