package hibernate.entity;
// Generated May 3, 2019 9:07:01 PM by Hibernate Tools 4.3.1


import java.sql.Clob;
import java.util.Date;

/**
 * Panen generated by hbm2java
 */
public class Panen  implements java.io.Serializable {


     private Integer id;
     private Date createdAt;
     private Double ukuranLahan;
     private String jenisTanaman;
     private Date tanggalMulaiPanen;
     private Date targetSelesaiPanen;
     private Clob deskripsiTanaman;
     private String lokasi;
     private String caraPanen;
     private Integer harga;
     private Double quantity;
     private String status;
     private String bookedStatus;

    public Panen() {
    }

    public Panen(Date createdAt, Double ukuranLahan, String jenisTanaman, Date tanggalMulaiPanen, Date targetSelesaiPanen, Clob deskripsiTanaman, String lokasi, String caraPanen, Integer harga, Double quantity, String status, String bookedStatus) {
       this.createdAt = createdAt;
       this.ukuranLahan = ukuranLahan;
       this.jenisTanaman = jenisTanaman;
       this.tanggalMulaiPanen = tanggalMulaiPanen;
       this.targetSelesaiPanen = targetSelesaiPanen;
       this.deskripsiTanaman = deskripsiTanaman;
       this.lokasi = lokasi;
       this.caraPanen = caraPanen;
       this.harga = harga;
       this.quantity = quantity;
       this.status = status;
       this.bookedStatus = bookedStatus;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Double getUkuranLahan() {
        return this.ukuranLahan;
    }
    
    public void setUkuranLahan(Double ukuranLahan) {
        this.ukuranLahan = ukuranLahan;
    }
    public String getJenisTanaman() {
        return this.jenisTanaman;
    }
    
    public void setJenisTanaman(String jenisTanaman) {
        this.jenisTanaman = jenisTanaman;
    }
    public Date getTanggalMulaiPanen() {
        return this.tanggalMulaiPanen;
    }
    
    public void setTanggalMulaiPanen(Date tanggalMulaiPanen) {
        this.tanggalMulaiPanen = tanggalMulaiPanen;
    }
    public Date getTargetSelesaiPanen() {
        return this.targetSelesaiPanen;
    }
    
    public void setTargetSelesaiPanen(Date targetSelesaiPanen) {
        this.targetSelesaiPanen = targetSelesaiPanen;
    }
    public Clob getDeskripsiTanaman() {
        return this.deskripsiTanaman;
    }
    
    public void setDeskripsiTanaman(Clob deskripsiTanaman) {
        this.deskripsiTanaman = deskripsiTanaman;
    }
    public String getLokasi() {
        return this.lokasi;
    }
    
    public void setLokasi(String lokasi) {
        this.lokasi = lokasi;
    }
    public String getCaraPanen() {
        return this.caraPanen;
    }
    
    public void setCaraPanen(String caraPanen) {
        this.caraPanen = caraPanen;
    }
    public Integer getHarga() {
        return this.harga;
    }
    
    public void setHarga(Integer harga) {
        this.harga = harga;
    }
    public Double getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getBookedStatus() {
        return this.bookedStatus;
    }
    
    public void setBookedStatus(String bookedStatus) {
        this.bookedStatus = bookedStatus;
    }




}


