package hibernate.entity;
// Generated May 3, 2019 9:07:01 PM by Hibernate Tools 4.3.1


import java.sql.Clob;
import java.util.Date;

/**
 * PascaPanen generated by hbm2java
 */
public class PascaPanen  implements java.io.Serializable {


     private Integer id;
     private Date createdAt;
     private Double ukuranLahan;
     private String jenisTanaman;
     private Date tanggalPascaPanen;
     private Date targetTanggalPanen;
     private Clob deskripsiTanaman;
     private String lokasi;
     private String banyakHasilPanen;
     private Integer harga;
     private String status;
     private String bookedStatus;

    public PascaPanen() {
    }

    public PascaPanen(Date createdAt, Double ukuranLahan, String jenisTanaman, Date tanggalPascaPanen, Date targetTanggalPanen, Clob deskripsiTanaman, String lokasi, String banyakHasilPanen, Integer harga, String status, String bookedStatus) {
       this.createdAt = createdAt;
       this.ukuranLahan = ukuranLahan;
       this.jenisTanaman = jenisTanaman;
       this.tanggalPascaPanen = tanggalPascaPanen;
       this.targetTanggalPanen = targetTanggalPanen;
       this.deskripsiTanaman = deskripsiTanaman;
       this.lokasi = lokasi;
       this.banyakHasilPanen = banyakHasilPanen;
       this.harga = harga;
       this.status = status;
       this.bookedStatus = bookedStatus;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Double getUkuranLahan() {
        return this.ukuranLahan;
    }
    
    public void setUkuranLahan(Double ukuranLahan) {
        this.ukuranLahan = ukuranLahan;
    }
    public String getJenisTanaman() {
        return this.jenisTanaman;
    }
    
    public void setJenisTanaman(String jenisTanaman) {
        this.jenisTanaman = jenisTanaman;
    }
    public Date getTanggalPascaPanen() {
        return this.tanggalPascaPanen;
    }
    
    public void setTanggalPascaPanen(Date tanggalPascaPanen) {
        this.tanggalPascaPanen = tanggalPascaPanen;
    }
    public Date getTargetTanggalPanen() {
        return this.targetTanggalPanen;
    }
    
    public void setTargetTanggalPanen(Date targetTanggalPanen) {
        this.targetTanggalPanen = targetTanggalPanen;
    }
    public Clob getDeskripsiTanaman() {
        return this.deskripsiTanaman;
    }
    
    public void setDeskripsiTanaman(Clob deskripsiTanaman) {
        this.deskripsiTanaman = deskripsiTanaman;
    }
    public String getLokasi() {
        return this.lokasi;
    }
    
    public void setLokasi(String lokasi) {
        this.lokasi = lokasi;
    }
    public String getBanyakHasilPanen() {
        return this.banyakHasilPanen;
    }
    
    public void setBanyakHasilPanen(String banyakHasilPanen) {
        this.banyakHasilPanen = banyakHasilPanen;
    }
    public Integer getHarga() {
        return this.harga;
    }
    
    public void setHarga(Integer harga) {
        this.harga = harga;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getBookedStatus() {
        return this.bookedStatus;
    }
    
    public void setBookedStatus(String bookedStatus) {
        this.bookedStatus = bookedStatus;
    }




}


