package hibernate.entity;
// Generated May 3, 2019 9:07:01 PM by Hibernate Tools 4.3.1


import java.sql.Clob;
import java.util.Date;

/**
 * Pembibitan generated by hbm2java
 */
public class Pembibitan  implements java.io.Serializable {


     private Integer id;
     private Date createdAt;
     private Double ukuranLahan;
     private String jenisTanaman;
     private Date tanggalPembibitan;
     private Date targetSelesaiPembibitan;
     private Clob deskripsiTanaman;
     private String lokasi;
     private String caraPembibitan;
     private String status;
     private String bookedStatus;

    public Pembibitan() {
    }

    public Pembibitan(Date createdAt, Double ukuranLahan, String jenisTanaman, Date tanggalPembibitan, Date targetSelesaiPembibitan, Clob deskripsiTanaman, String lokasi, String caraPembibitan, String status, String bookedStatus) {
       this.createdAt = createdAt;
       this.ukuranLahan = ukuranLahan;
       this.jenisTanaman = jenisTanaman;
       this.tanggalPembibitan = tanggalPembibitan;
       this.targetSelesaiPembibitan = targetSelesaiPembibitan;
       this.deskripsiTanaman = deskripsiTanaman;
       this.lokasi = lokasi;
       this.caraPembibitan = caraPembibitan;
       this.status = status;
       this.bookedStatus = bookedStatus;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Double getUkuranLahan() {
        return this.ukuranLahan;
    }
    
    public void setUkuranLahan(Double ukuranLahan) {
        this.ukuranLahan = ukuranLahan;
    }
    public String getJenisTanaman() {
        return this.jenisTanaman;
    }
    
    public void setJenisTanaman(String jenisTanaman) {
        this.jenisTanaman = jenisTanaman;
    }
    public Date getTanggalPembibitan() {
        return this.tanggalPembibitan;
    }
    
    public void setTanggalPembibitan(Date tanggalPembibitan) {
        this.tanggalPembibitan = tanggalPembibitan;
    }
    public Date getTargetSelesaiPembibitan() {
        return this.targetSelesaiPembibitan;
    }
    
    public void setTargetSelesaiPembibitan(Date targetSelesaiPembibitan) {
        this.targetSelesaiPembibitan = targetSelesaiPembibitan;
    }
    public Clob getDeskripsiTanaman() {
        return this.deskripsiTanaman;
    }
    
    public void setDeskripsiTanaman(Clob deskripsiTanaman) {
        this.deskripsiTanaman = deskripsiTanaman;
    }
    public String getLokasi() {
        return this.lokasi;
    }
    
    public void setLokasi(String lokasi) {
        this.lokasi = lokasi;
    }
    public String getCaraPembibitan() {
        return this.caraPembibitan;
    }
    
    public void setCaraPembibitan(String caraPembibitan) {
        this.caraPembibitan = caraPembibitan;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getBookedStatus() {
        return this.bookedStatus;
    }
    
    public void setBookedStatus(String bookedStatus) {
        this.bookedStatus = bookedStatus;
    }




}


