package hibernate.entity;
// Generated May 3, 2019 9:07:01 PM by Hibernate Tools 4.3.1


import java.sql.Clob;
import java.util.Date;

/**
 * Pemupukan generated by hbm2java
 */
public class Pemupukan  implements java.io.Serializable {


     private Integer id;
     private Date createdAt;
     private Double ukuranLahan;
     private String jenisTanaman;
     private Date tanggalPemupukan;
     private Date targetSelesaiPemupukan;
     private Clob deskripsiTanaman;
     private String lokasi;
     private String caraPemupukan;
     private Integer jumlahTanaman;
     private Double jumlahPupuk;
     private String status;
     private String bookedStatus;

    public Pemupukan() {
    }

    public Pemupukan(Date createdAt, Double ukuranLahan, String jenisTanaman, Date tanggalPemupukan, Date targetSelesaiPemupukan, Clob deskripsiTanaman, String lokasi, String caraPemupukan, Integer jumlahTanaman, Double jumlahPupuk, String status, String bookedStatus) {
       this.createdAt = createdAt;
       this.ukuranLahan = ukuranLahan;
       this.jenisTanaman = jenisTanaman;
       this.tanggalPemupukan = tanggalPemupukan;
       this.targetSelesaiPemupukan = targetSelesaiPemupukan;
       this.deskripsiTanaman = deskripsiTanaman;
       this.lokasi = lokasi;
       this.caraPemupukan = caraPemupukan;
       this.jumlahTanaman = jumlahTanaman;
       this.jumlahPupuk = jumlahPupuk;
       this.status = status;
       this.bookedStatus = bookedStatus;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Double getUkuranLahan() {
        return this.ukuranLahan;
    }
    
    public void setUkuranLahan(Double ukuranLahan) {
        this.ukuranLahan = ukuranLahan;
    }
    public String getJenisTanaman() {
        return this.jenisTanaman;
    }
    
    public void setJenisTanaman(String jenisTanaman) {
        this.jenisTanaman = jenisTanaman;
    }
    public Date getTanggalPemupukan() {
        return this.tanggalPemupukan;
    }
    
    public void setTanggalPemupukan(Date tanggalPemupukan) {
        this.tanggalPemupukan = tanggalPemupukan;
    }
    public Date getTargetSelesaiPemupukan() {
        return this.targetSelesaiPemupukan;
    }
    
    public void setTargetSelesaiPemupukan(Date targetSelesaiPemupukan) {
        this.targetSelesaiPemupukan = targetSelesaiPemupukan;
    }
    public Clob getDeskripsiTanaman() {
        return this.deskripsiTanaman;
    }
    
    public void setDeskripsiTanaman(Clob deskripsiTanaman) {
        this.deskripsiTanaman = deskripsiTanaman;
    }
    public String getLokasi() {
        return this.lokasi;
    }
    
    public void setLokasi(String lokasi) {
        this.lokasi = lokasi;
    }
    public String getCaraPemupukan() {
        return this.caraPemupukan;
    }
    
    public void setCaraPemupukan(String caraPemupukan) {
        this.caraPemupukan = caraPemupukan;
    }
    public Integer getJumlahTanaman() {
        return this.jumlahTanaman;
    }
    
    public void setJumlahTanaman(Integer jumlahTanaman) {
        this.jumlahTanaman = jumlahTanaman;
    }
    public Double getJumlahPupuk() {
        return this.jumlahPupuk;
    }
    
    public void setJumlahPupuk(Double jumlahPupuk) {
        this.jumlahPupuk = jumlahPupuk;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getBookedStatus() {
        return this.bookedStatus;
    }
    
    public void setBookedStatus(String bookedStatus) {
        this.bookedStatus = bookedStatus;
    }




}


