package hibernate.entity;
// Generated May 3, 2019 9:07:01 PM by Hibernate Tools 4.3.1


import java.sql.Clob;
import java.util.Date;

/**
 * Penanaman generated by hbm2java
 */
public class Penanaman  implements java.io.Serializable {


     private Integer id;
     private Date createdAt;
     private Double ukuranLahan;
     private String jenisTanaman;
     private Date tanggalPenanaman;
     private Date targetSelesaiPenanaman;
     private Clob deskripsiTanaman;
     private String lokasi;
     private String caraPenanaman;
     private String status;
     private String bookedStatus;

    public Penanaman() {
    }

    public Penanaman(Date createdAt, Double ukuranLahan, String jenisTanaman, Date tanggalPenanaman, Date targetSelesaiPenanaman, Clob deskripsiTanaman, String lokasi, String caraPenanaman, String status, String bookedStatus) {
       this.createdAt = createdAt;
       this.ukuranLahan = ukuranLahan;
       this.jenisTanaman = jenisTanaman;
       this.tanggalPenanaman = tanggalPenanaman;
       this.targetSelesaiPenanaman = targetSelesaiPenanaman;
       this.deskripsiTanaman = deskripsiTanaman;
       this.lokasi = lokasi;
       this.caraPenanaman = caraPenanaman;
       this.status = status;
       this.bookedStatus = bookedStatus;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Double getUkuranLahan() {
        return this.ukuranLahan;
    }
    
    public void setUkuranLahan(Double ukuranLahan) {
        this.ukuranLahan = ukuranLahan;
    }
    public String getJenisTanaman() {
        return this.jenisTanaman;
    }
    
    public void setJenisTanaman(String jenisTanaman) {
        this.jenisTanaman = jenisTanaman;
    }
    public Date getTanggalPenanaman() {
        return this.tanggalPenanaman;
    }
    
    public void setTanggalPenanaman(Date tanggalPenanaman) {
        this.tanggalPenanaman = tanggalPenanaman;
    }
    public Date getTargetSelesaiPenanaman() {
        return this.targetSelesaiPenanaman;
    }
    
    public void setTargetSelesaiPenanaman(Date targetSelesaiPenanaman) {
        this.targetSelesaiPenanaman = targetSelesaiPenanaman;
    }
    public Clob getDeskripsiTanaman() {
        return this.deskripsiTanaman;
    }
    
    public void setDeskripsiTanaman(Clob deskripsiTanaman) {
        this.deskripsiTanaman = deskripsiTanaman;
    }
    public String getLokasi() {
        return this.lokasi;
    }
    
    public void setLokasi(String lokasi) {
        this.lokasi = lokasi;
    }
    public String getCaraPenanaman() {
        return this.caraPenanaman;
    }
    
    public void setCaraPenanaman(String caraPenanaman) {
        this.caraPenanaman = caraPenanaman;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getBookedStatus() {
        return this.bookedStatus;
    }
    
    public void setBookedStatus(String bookedStatus) {
        this.bookedStatus = bookedStatus;
    }




}


